modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "findme"
version = "${version}"
displayName = "FindMe"
authors = "Buuz135"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.findme]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.findme]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.findme]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"