name: Publish action

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build
      - name: Publish Minecraft Mods Forge
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          curseforge-id: 291936
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: forge/build/libs/!(*-@(dev|sources)).jar
          files-secondary: forge/build/libs/*-@(dev|sources).jar
          version-type: beta
          loaders: forge
          game-versions: 1.18.1
          dependencies: |
            architectury-forge | depends
      - name: Publish Minecraft Mods Fabric
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          curseforge-id: 291936
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: fabric/build/libs/!(*-@(dev|sources)).jar
          files-secondary: fabric/build/libs/*-@(dev|sources).jar
          version-type: beta
          loaders: fabric
          game-versions: 1.18.1
          dependencies: |
            architectury-fabric | depends
          changelog: "https://github.com/Buuz135/FindMe/commits/1.18"