name: Publish action

on:
  push:
    branches:
      - '1.18'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods Forge
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          curseforge-id: 291936
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: forge/build/libs/!(*-@(dev|sources)).jar
          files-secondary: forge/build/libs/*-@(dev|sources).jar
          version-type: beta
          loaders: forge
          game-versions: 1.18.1
          dependencies: |
            architectury-forge | depends
      - name: Publish Minecraft Mods Fabric
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          curseforge-id: 291936
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-primary: fabric/build/libs/!(*-@(dev|sources)).jar
          files-secondary: fabric/build/libs/*-@(dev|sources).jar
          version-type: beta
          loaders: fabric
          game-versions: 1.18.1
          dependencies: |
            architectury-fabric | depends
          changelog: "https://github.com/Buuz135/FindMe/commits/1.18"